export const LOAD_EXPERIENCE_SUCCESS = "LOAD_EXPERIENCE_SUCCESS";
export const LOAD_EXPERIENCE_FAILURE = "LOAD_EXPERIENCE_FAILURE";

export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";
export const LOAD_PROJECTS_FAILURE = "LOAD_PROJECTS_FAILURE";

export const LOAD_TAGS_SUCCESS = "LOAD_TAGS_SUCCESS";
export const LOAD_TAGS_FAILURE = "LOAD_TAGS_FAILURE";

export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_FAILURE = "LOAD_PROFILE_FAILURE";

export const EMAIL_SEND_SUCCESS = "EMAIL_SEND_SUCCESS";
export const EMAIL_SEND_FAILURE = "EMAIL_SEND_FAILURE";
export const EMAIL_LOADING = "EMAIL_LOADING";
export const EMAIL_INITIAL = "EMAIL_INITIAL";
export const EMAIL_ALL_FILLIN = "EMAIL_ALL_FILLIN";
